INSERT INTO PRODUTO VALUES ('001', 'Produto 1', 'A');
INSERT INTO PRODUTO VALUES ('002', 'Produto 2', 'A');

INSERT INTO PRODUTO_COSIF VALUES ('001', 'COSIF1', 'CLASS1', 'A');
INSERT INTO PRODUTO_COSIF VALUES ('002', 'COSIF2', 'CLASS2', 'A');