CREATE TABLE PRODUTO (
    COD_PRODUTO VARCHAR(4) PRIMARY KEY,
    DES_PRODUTO VARCHAR(30),
    STA_STATUS CHAR(1)
);

CREATE TABLE PRODUTO_COSIF (
    COD_PRODUTO VARCHAR(4),
    COD_COSIF VARCHAR(11),
    COD_CLASSIFICACAO VARCHAR(6),
    STA_STATUS CHAR(1),
    PRIMARY KEY (COD_PRODUTO, COD_COSIF)
);

CREATE TABLE MOVIMENTO_MANUAL (
    DAT_MES INT,
    DAT_ANO INT,
    NUM_LANCAMENTO INT,
    COD_PRODUTO VARCHAR(4),
    COD_COSIF VARCHAR(11),
    DES_DESCRICAO VARCHAR(50),
    DAT_MOVIMENTO TIMESTAMP,
    COD_USUARIO VARCHAR(15),
    VAL_VALOR DECIMAL(18,2),
    PRIMARY KEY (DAT_MES, DAT_ANO, NUM_LANCAMENTO)
);